version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install NPM dependecies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Compile typescript code into /dist
          command: yarn build

      - run:
          name: Install JUnit coverage reporter
          command: yarn add --dev jest-junit

      - run:
          name: Run tests with JUnit as reporter
          command: yarn test:coverage
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"

      - store_test_results:
          path: reports/junit

      - store_artifacts:
          path: reports/junit

      - store_artifacts:
          path: coverage

      - codecov/upload:
          file: coverage/coverage_final.json
