name: Test, coverage and deploy Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Yarn install and test with coverage generation
        run: |
          yarn
          yarn test:coverage
        if: success()
      - name: Codecov upload
        uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
        if: success()
      - name: Docker build & push
        uses: HurricanKai/Publish-Docker-Github-Action@master
        with:
          name: slavalab/be-dice-server
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
